### ISSUE TITLE
Net::ReadTimeout on Test Suite

### ISSUE THREAD

**Issue by mkanthan** [jasmine/jasmine_selenium_runner#5]
As of a few days ago, upon running `rake jasmine:ci` on the command line, I get the following output:

```
$ be rake jasmine:ci --trace
** Invoke jasmine:ci (first_time)
** Invoke jasmine:require_json (first_time)
** Execute jasmine:require_json
** Invoke jasmine:require (first_time)
** Execute jasmine:require
** Invoke jasmine:configure (first_time)
** Execute jasmine:configure
** Invoke jasmine:configure_plugins (first_time)
** Execute jasmine:configure_plugins
** Execute jasmine:ci
Waiting for jasmine server on 57381...
Waiting for jasmine server on 57381...
[2016-06-21 10:09:48] INFO  WEBrick 1.3.1
[2016-06-21 10:09:48] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin15]
[2016-06-21 10:09:48] INFO  WEBrick::HTTPServer#start: pid=68494 port=57381
Waiting for jasmine server on 57381...
jasmine server started
Waiting for suite to finish in browser ...
[2016-06-21 10:10:05] ERROR Errno::EPROTOTYPE: Protocol wrong type for socket
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `write'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `<<'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `_write_data'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:433:in `send_body_string'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:307:in `send_body'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:209:in `send_response'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:112:in `run'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2016-06-21 10:10:05] ERROR Errno::EPROTOTYPE: Protocol wrong type for socket
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `write'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `<<'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `_write_data'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:433:in `send_body_string'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:307:in `send_body'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:209:in `send_response'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:112:in `run'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2016-06-21 10:10:05] ERROR Errno::EPROTOTYPE: Protocol wrong type for socket
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `write'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `<<'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:461:in `_write_data'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:433:in `send_body_string'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:307:in `send_body'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpresponse.rb:209:in `send_response'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:112:in `run'
	/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
rake aborted!
Net::ReadTimeout
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:853:in `start'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:627:in `execute'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:353:in `executeScript'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/driver.rb:220:in `execute_script'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/jasmine_selenium_runner-2.4.0/lib/jasmine/runners/selenium.rb:32:in `finished?'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/jasmine_selenium_runner-2.4.0/lib/jasmine/runners/selenium.rb:49:in `wait_for_suites_to_finish_running'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/jasmine_selenium_runner-2.4.0/lib/jasmine/runners/selenium.rb:16:in `run'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/jasmine-2.4.0/lib/jasmine/ci_runner.rb:37:in `run'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/jasmine-2.4.0/lib/jasmine/tasks/jasmine.rake:47:in `block (2 levels) in <top (required)>'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/SoftwareDev/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/bin/rake:23:in `load'
/Users/SoftwareDev/.rbenv/versions/2.3.0/gemsets/global/bin/rake:23:in `<main>'
Tasks: TOP => jasmine:ci
[2016-06-21 10:10:57] INFO  going to shutdown ...
[2016-06-21 10:10:57] INFO  WEBrick::HTTPServer#start done.
```

It fails with a `Net::ReadTimeout` error seemingly thrown from `selenium-webdriver`.

I can see the test suite running in FireFox but FireFox will exit prematurely before reaching the end of the suite, coinciding with this error. Furthermore, I had a hunch that it has to do with the length of the suite (being a timeout error), and it found out that it might - if I were to `xdescribe` some of my longer Spec files, it reaches the end of the suite and shows me the report, albeit still giving me this error and exiting after a few seconds.

Running the jasmine suite normally via `rake jasmine` and navigating FireFox to `localhost:8888` works fine which leads me to believe it's an issue in either selenium or jasmine_selenium_runner.

This worked fine up until Friday, June 17, 2016. I even moved my repository back nearly a week to see if it was a commit I made - and it wasn't. I still get the same issue - and on 3 different machines, so I know it is related to my project or the environment, but I'm not sure what it is, or what changed on that day, causing the issue.

**Comment by mkanthan** [comment]
I solved this. It turns out that my test fixture data contained image references to a site that seems be down - but not timing out on loading the pictures. Disabling these tests did the trick. I didn't do any debugging to figure out if the test runner could potentially handle this a little better and give us a little more feedback with the timeout error, although that would be nice.
