### ISSUE TITLE
jsApiReporter is not defined

### ISSUE THREAD

**Issue by bjeanes** [jasmine/jasmine_selenium_runner#6]
Using the latest version of this gem and of Jasmine, I get the following when trying to run with remote Selenium:

```
♪  SELENIUM_URL=http://localhost:4444/wd/hub rake 'jasmine:ci[false]'
[21583] Puma starting in cluster mode...
[21583] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
[21583] * Min threads: 1, max threads: 1
[21583] * Environment: development
[21583] * Process workers: 1
[21583] * Preloading application
[21583] * Listening on tcp://0.0.0.0:65115
[21583] Use Ctrl-C to stop
[21583] - Worker 0 (pid: 21625) booted, phase: 0
Waiting for server on localhost:65115...
jasmine server started
rake aborted!
Selenium::WebDriver::Error::UnknownError: unknown error: jsApiReporter is not defined
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.9.93-boot2docker x86_64)
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/oss/bridge.rb:267:in `execute_script'
/Users/bjeanes/.gem/ruby/2.5.3/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:211:in `execute_script'
/Users/bjeanes/.gem/ruby/2.5.3/gems/jasmine_selenium_runner-3.0.0/lib/jasmine/runners/selenium.rb:28:in `started?'
/Users/bjeanes/.gem/ruby/2.5.3/gems/jasmine_selenium_runner-3.0.0/lib/jasmine/runners/selenium.rb:41:in `ensure_connection_established'
/Users/bjeanes/.gem/ruby/2.5.3/gems/jasmine_selenium_runner-3.0.0/lib/jasmine/runners/selenium.rb:15:in `run'
/Users/bjeanes/.gem/ruby/2.5.3/gems/jasmine-3.3.0/lib/jasmine/ci_runner.rb:37:in `run'
/Users/bjeanes/.gem/ruby/2.5.3/gems/jasmine-3.3.0/lib/jasmine/tasks/jasmine.rake:55:in `block (2 levels) in <main>'
/Users/bjeanes/.gem/ruby/2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => jasmine:ci
```

Running locally _does_ work, though...

**Comment by bjeanes** [comment]
This turned out to be because Jasmine is directing the remote Selenium WebDriver to connect to "http://localhost".

The fix is to properly set Jasmine's `host` configuration option. In my case, I'm running the tests and the selenium instance in Docker and I know they are on the same network but the IP addresses are not constant.

My fix was:

``` ruby
Jasmine.configure do |config|
  # existing config here

  if ENV['SELENIUM_URL']
    require 'socket'
    ip = Socket.ip_address_list.
      detect(&:ipv4_private?).
      ip_address
    config.host = "http://#{ip}"
  end
end
```

but realistically, I could be using a hostname that I know would resolve, e.g. `config.host = "http://tests"`, but for reasons specific to my setup I don't want to couple this configuration to the service name in `docker-compose.yml`.
